# Generated by Django 4.2.7 on 2023-11-25 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HouseModel",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("area", models.IntegerField()),
                ("floor", models.IntegerField()),
                ("city", models.CharField(db_index=True, max_length=50)),
                ("price", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("FREE", "FREE"), ("BAUGHT", "BAUGHT")],
                        db_index=True,
                        default="FREE",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
