# Generated by Django 4.2.7 on 2023-11-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="housemodel",
            name="city",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="housemodel",
            name="status",
            field=models.CharField(
                choices=[("FREE", "FREE"), ("BAUGHT", "BAUGHT")],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
